### ISSUE TITLE
Add links to refine.bio docs for more info

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-py#36]
We need to add links to refine.bio docs to help users gain understanding of what certain functions mean. 

For example: When we talk about `aggregation` and `transformation` options for download, it would be super helpful to provide links to those section in the docs for user who want to know exactly what happens if they choose those options. 

So we need to compile a list of places where it would be good link back to refine.bio docs. 

I shall scour the docs and compile a list.

**Comment by samuel-tate** [comment]
@dvenprasad I think this Issue might have been addressed as we updated the docs and improved the error messages.

Is this issue good to be closed?

**Comment by dvenprasad** [comment]
Everything in Quick start and Using the CLI seems to be linked. Closing the issue
