### ISSUE TITLE
Typo in documentation about high-level function for downloading compendia

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-py#47]
From @cgreene 

> is this function name a typo? https://alexslemonade.github.io/refinebio-py/high_level_functions.html#pyrefinebio.high_level_functions.download_quandfile_compendium

I think this is a typo in the docs because:

https://github.com/AlexsLemonade/refinebio-py/blob/9d9ee1fffe1db2ac5e45089a982434d44c4134b1/pyrefinebio/high_level_functions.py#L201

**Comment by samuel-tate** [comment]
This typo was addressed in #42 

https://github.com/AlexsLemonade/refinebio-py/pull/42/files#diff-2bbedd13cfba1db572820a90f3d61d13b85d171a926091b42acb056acf409773R208

**Comment by jaclyn-taroni** [comment]
Feel free to close once the change gets deployed to GH pages!

**Comment by kurtwheeler** [comment]
The docs have been deployed! This is fixed!
