### ISSUE TITLE
`add_samples()` method for Dataset class

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio-py#9]
The Dataset class needs to have it's `data` attribute properly formatted. We have an opportunity to make this easier if we add an `add_samples(experiment, samples=["ALL"])` method. This would allow us to make an example that looks something like:
```python
dataset = Dataset()
# Get all samples for experiment GSE1234
dataset.add_samples("GSE1234")
# Get only a couple samples for experiment GSE12345
dataset.add_samples("GSE12345", ["GSM123", "GSM124"])
dataset.process()

import time
while not dataset.check()
  time.sleep(10)

dataset.download("my_dataset.zip")
```

**Comment by kurtwheeler** [comment]
Oooooh, what if we had `add_samples` return the updated Dataset so someone could do:
```python
Dataset().add_samples("GSE1234").add_samples("GSE12345", ["GSM123", "GSM124"]).process()
```

**Comment by cgreene** [comment]
☝️  i like that

**Comment by cgreene** [comment]
also please have a test that after calling process you can't add more samples 😁

**Comment by samuel-tate** [comment]
Added as a part of #11
